# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-14 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GastosMensuales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.AddField(
            model_name='producto',
            name='gasto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Gastos', to='GastosMensuales.Gasto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Categorias', to='GastosMensuales.Categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.FloatField(),
        ),
    ]
